---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: kong
  namespace: demo
  annotations:
    fluxcd.io/automated: "false"
    fluxcd.io/tag.chart-image: glob:3.1.1-debian-9-*
spec:
  releaseName: kong
  chart:
    git: ssh://git@github.com/brunofitas/cluster
    ref: master
    path: charts/kong
  values: {}
